### ISSUE TITLE
crashed when connecting two tesla coil

### ISSUE THREAD

**Issue by alpha8196** [gunnerwolf/TeslaCoils#14] opened 2016-10-01 02:01 UTC
as title
using tesla coils 0.2.1.0
crash report [http://paste.ee/p/DMPxa](url)

**Comment by kreezxil** [comment] 2016-10-22 16:16
confirmed same version too but with forge build 2107

http://paste.ee/p/lczxq

**Comment by dylanrenwick** [comment] 2016-12-02 09:24
Both paste.ee links are returning a 404 error, so I'm going to assume they were both abstract method errors. Been fixed in the latest PR, will push an update out on curseforge in the next couple of days.

**Closed as completed by dylanrenwick** 2016-12-02 09:24 UTC

**Comment by kreezxil** [comment] 2016-12-02 16:39
They're returning that because they have expired. Paste.ee defaults to 30 days

-----Original Message-----
